language: c
sudo: false

addons:
  apt:
    packages:
    - asciidoc
    - xmlto
    - valgrind

env:
  - TIG_BUILD=autoconf
  - TIG_BUILD=config.make

compiler:
  - gcc
  - clang

script: tools/travis.sh

matrix:
  include:
  - env: TIG_BUILD=valgrind
    script: tools/travis.sh
  - env: TIG_BUILD=address-sanitizer
    compiler: clang
    # LeakSanitizer requires ptrace capabilities
    # https://github.com/travis-ci/travis-ci/issues/9033
    sudo: required
    script: tools/travis.sh
  - if: branch = master
    os: osx
    env:
    compiler: clang
    script: HOMEBREW_NO_AUTO_UPDATE=1 brew install --HEAD tig
  - if: branch = master
    os: osx
    env:
    compiler: gcc
    script: HOMEBREW_NO_AUTO_UPDATE=1 brew install --HEAD tig
